image: microsoft/dotnet:2.1-sdk

stages:
    - build
    - test
    - release

build and create nupkgs:
    stage: build
    script:
        - dotnet build Wumpus.Commands.sln -c Release /p:BuildId="$CI_PIPELINE_IID" /p:Tag="$CI_COMMIT_TAG"
        - dotnet pack Wumpus.Commands.sln -c Release -o artifacts /p:BuildId="$CI_PIPELINE_IID" /p:Tag="$CI_COMMIT_TAG"

run unit tests:
    stage: test
    script:
        - dotnet test Wumpus.Commands.Tests.sln -c Release /p:BuildId="$CI_PIPELINE_IID" /p:Tag="$CI_COMMIT_TAG"
